[build]
  publish = "build/web"
  command = "flutter build web --web-renderer canvaskit"
  
[build.environment]
  FLUTTER_VERSION = "3.19.0"
  
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  
[[redirects]]
  from = "/flutter.js"
  to = "/flutter.js"
  status = 200
  
[[redirects]]
  from = "/flutter_bootstrap.js"
  to = "/flutter_bootstrap.js"
  status = 200
  
[[redirects]]
  from = "/flutter_service_worker.js"
  to = "/flutter_service_worker.js"
  status = 200
  
[[redirects]]
  from = "/main.dart.js"
  to = "/main.dart.js"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
